language: python
python:
- 3.8
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: Iolaum
  password:
    secure: aAQiEpU08XswWeD5xvHVB929JlwI18XL7vcPDsGSFfXw6gz6J6pcWFF+D/9r7zwtzcn9JV34V0WeYeZ20zRYYqx0CFxFVyNz75kUvUH5R/rF24w+oaH7K6+CPZKNtYTApkpvBbNANR/ZoYao7DQmzWZI/uczoQYQBpprK2WsfnVJlS2mYpkzAcJ/DAvBllOW13lP2Hc6xOMLlVTlxOoJ8v0VHjgD6oRKwCwlbkqDZl0RdAfsNoc/+8jPmn8GnplyhiifUcd0jcTZtCopTGHKsmLzlS7jgBiR0qfLSmftdToNEd+F5bTFYELIGmU4o9ljUV/3QZXnPsqpcc8WQpOQ9x5+HYGAh955TefGIbvMDus63yiasNFB70JLn5W2brAkk7OJN75hBBFxYCPv5oz2Dcb6UHH0jK2Nx3sF4Zkshua9wByIll17qpfD8dBA+7Jj7kDhWmqiqqfDKHjONDwPjoh1t1YFtG8dbtIKODbj9/Dp8VVzKQ3vgS5Hdmyv5PweDqNfN0CBqvqajJhFEJGbQs7vVcE5x0Ew6DxzHxQdfORrTpdmY5425cZP5wn+TVccvR5s6g0iOITV0RdQWK8Q33++FhvAU1LZKIggV/F+EnMpenW0Ry8rPjDaGL6wDfBfhAroBX1brwvGEtqEBLiFauMuju+wb0mqgdYFVbCKiTI=
  on:
    tags: true
    repo: Iolaum/podcust
    python: 3.8
