---
dist: focal
language: python
services: docker
python:
  - 3.8
jobs:
  include:
    - stage: "docker-fedora"
      name: "Test within Fedora Image"
      # Create a fedora docker image
      install:
        - docker build -t fedora .
      script:
        - docker run fedora /bin/sh -c "cd /src; make code; make test"
    - stage: "tox"
      name: "Test everything with tox"
      install: pip install -U tox-travis
      script: tox && make clean
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  username: "__token__"
  password:
    # yamllint disable-line rule:line-length
    secure: rH4wPa2TgWUoNV+0T4gEXf36Hav9Ko/RcPghYgqMhXIDGPDxTWAOjsBhkLvmRG9eA5ME61OJE6250G3FKH9j2qTfLq0Jt9bX5Nr/dh9xdtYtpIaCZgaYHzslMzjzBXVBX9McN70Jhh7okpeqUvgQ6tA0JJdkr5BzQlVDFbatSUu1psr1A9fGLeVZ0CnFk2M6JW7EditGU0uC1dKZlJszRrholobG2/FzRXwhf+M3mB846M1kMrQEgyrEn+tqz3FY3ddulsOAwqqwz4d6zdnYl6jRARIxhm5Fh5kYxlCi/uiTrityrxr54uiBlx623qI3gi1AKEbTOlBbFMDbiLUey8n38ltcHerDJr/j06X7Cajj0CgBaY/dYp5ixBLU+OlYMYl6OuxyCZIMZllGe3oGl4dR1PHZIfg5eSDCosJIzV/mRy/F+/7aNCQ8OlSOm4tH/CcB/E2Jc9twvPYJkGifVPk2eJ8QbDDSdfWq5NAUu7fTnYjT2gnjbOxbY44LN1eUtpYoo5vF1fcWiItNeDGG8t25veKBy/E6WrNeOid1byLVEz9qwY6qDCJH97q3J4pMeLTRdYcBAZhiCJGyMks/mtnIt2BHCVkO0zPewW6UHTkIulOhazzmWLIp2Njma2LyDe4OmJbWrrW2xSfkW6J/KJl1PVMUem/GqHgYh5JQGsE=
  skip_existing: true
  on:
    tags: true
    repo: Iolaum/podcust
    python: 3.8
